_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
accumulate_steps:
    value: 2
batch_size:
    value: 8
discrepancy:
    value: ce_and_entropy
json_path:
    value: results/test_mmlu_discrepancy.json
learning_rate:
    value: 1e-05
metric_mean:
    value:
        - 3.753156928976459
        - 0.6010761196819145
metric_std:
    value:
        - 3.533519151235875
        - 0.40142649109500755
model_name:
    value: Qwen/Qwen2.5-3B-Instruct
num_epochs:
    value: 25
output_dir:
    value: /network/scratch/m/matthew.macdermott/mc_distill
